name: Gut

on:
  pull_request:
  push:
    branches: [godot, godot-ci]

jobs:
  gut:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Gut (gut.sh)
        run: |
          chmod +x ./gut.sh
          ./gut.sh
